### PR TITLE
fix: improve error message for not yet archived historical weather

### LINKED ISSUE #135: [Bug Report] Historical Data not Available
I was testing options for a solution to #132 and noticed that the application breaks if historical weather data is queried.  Here are some examples:

- ``` wthrr London -F `date --date=tomorrow +%F` ```
- ``` wthrr London -F `date +%F` ```
- ``` wthrr London -F `date --date=yesterday +%F` ```
- `wthrr London -F 2023-05-07` (tomorrow)
- `wthrr London -F 2023-05-06` (today)
- `wthrr London -F 2023-05-05` (yesterday)

I understand that for future dates, there is no data to be fetched, yet.  But the application offers historical weather data, so I assume that historical data should be available, at least for some places like capital cities and for dates in the past.  As a core functionality of the application does not work, I consider this bug critical.

### PR DESCRIPTION
**Pull request by ttytm**
An improved error message for historical weather data that is not yet available in open-meteo's archives. 

Resolves #135

### CODE REVIEW

File: src/modules/weather.rs [hunk 1]
```diff
@@ -125,13 +126,23 @@ latitude={lat}
...
+		let raw_res = reqwest::get(url)
 			.await?
-			.json::<OptionalWeather>()
+			.json::<Value>()
 			.await
 			.with_context(|| "Historical weather data request failed.")?;
 
-		Ok(res)
+		// It takes up to 5 days until temperature data is available in open-meteo's archive.
+		// Therefor we check for null values in the temperature.
```
Comment (kevinmatthes) [inline src/modules/weather.rs:136]:
```suggestion
		// Therefore, we check for null values in the temperature.
```

File: src/modules/weather.rs [hunk 2]
```diff
@@ -125,13 +126,23 @@ latitude={lat}
...
+		if raw_res["hourly"]["temperature_2m"]
+			.as_array()
+			.expect("Failed decoding temperature data for historical weather.")[0]
+			.is_null()
+		{
+			return Err(anyhow!("The temperature for the requested weather has not yet been archived."));
```
Comment (kevinmatthes) [inline src/modules/weather.rs:142]:
```suggestion
			return Err(anyhow!("The temperature for the requested day has not yet been archived."));
```

**Review by kevinmatthes — CHANGES_REQUESTED** [review]
Thank you for your work on this, @tobealive!  I had a look on your changes and found two minor issues which might need to be adjusted.

**Comment by ttytm** [comment]
Thank you @kevinmatthes  
I'm gonna add a test case before merging to follow a good practice here.

**Review by kevinmatthes — APPROVED** [review]

**Comment by ttytm** [comment]
Now it just became an different API request if the requested date is younger than 5 days, instead additionally needing to check for null values. I would therefore merge this without adding a test for this function.
